export const tableRows = [
    {
        name: "Tony Reichert",
        role: "CEO",
        status: "Active",
        link: "/auth/1",
    },
    {
        name: "Zoey Lang",
        role: "Technical Lead",
        status: "Paused",
        link: "/auth/2",
    },
    {
        name: "Jane Fisher",
        role: "Senior Developer",
        status: "Active",
        link: "/auth/3",
    },
    {
        name: "William Howard",
        role: "Community Manager",
        status: "Vacation",
        link: "/auth/4",
    },
    {
        name: "Tony Reichert",
        role: "CEO",
        status: "Active",
        link: "/auth/1",
    },
    {
        name: "Zoey Lang",
        role: "Technical Lead",
        status: "Paused",
        link: "/auth/2",
    },
    {
        name: "Jane Fisher",
        role: "Senior Developer",
        status: "Active",
        link: "/auth/3",
    },
    {
        name: "William Howard",
        role: "Community Manager",
        status: "Vacation",
        link: "/auth/4",
    },
    {
        name: "Tony Reichert",
        role: "CEO",
        status: "Active",
        link: "/auth/1",
    },
    {
        name: "Zoey Lang",
        role: "Technical Lead",
        status: "Paused",
        link: "/auth/2",
    },
    {
        name: "Jane Fisher",
        role: "Senior Developer",
        status: "Active",
        link: "/auth/3",
    },
    {
        name: "William Howard",
        role: "Community Manager",
        status: "Vacation",
        link: "/auth/4",
    },
    {
        name: "Tony Reichert",
        role: "CEO",
        status: "Active",
        link: "/auth/1",
    },
    {
        name: "Zoey Lang",
        role: "Technical Lead",
        status: "Paused",
        link: "/auth/2",
    },
    {
        name: "Jane Fisher",
        role: "Senior Developer",
        status: "Active",
        link: "/auth/3",
    },
    {
        name: "William Howard",
        role: "Community Manager",
        status: "Vacation",
        link: "/auth/4",
    },
    {
        name: "Tony Reichert",
        role: "CEO",
        status: "Active",
        link: "/auth/1",
    },
    {
        name: "Zoey Lang",
        role: "Technical Lead",
        status: "Paused",
        link: "/auth/2",
    },
    {
        name: "Jane Fisher",
        role: "Senior Developer",
        status: "Active",
        link: "/auth/3",
    },
    {
        name: "William Howard",
        role: "Community Manager",
        status: "Vacation",
        link: "/auth/4",
    },
];
